### ISSUE TITLE
file location

### ISSUE THREAD

**Issue by musdfakoc** [sepidsh/Housegan-data-reader#5]
Hey there, thanks for the great work. I tried to run your code yet I get this error about file location and I could not figure out how to resolve this. I would appreciate if you can help.

FileNotFoundError: [Errno 2] No such file or directory: '../../../../../guriv-64/hg_rooms/Desktop/ITU_MBL/ArcMatic/houseganpp-main/Housegan-data-reader-main/rplandataset/floorplan_dataset/1.json'

**Comment by SuroshAhmadZobair** [comment]
Hi. 
same here:
FileNotFoundError: [Errno 2] No such file or directory: '../../../../../guriv-64/hg_rooms/.json'

Here is the command i used:
`python raster_to_json.py --path ../datasets/5039.png`

**Comment by SuroshAhmadZobair** [comment]
Found the solution!

chnage  line 276 in `raster_to_json.py` with the following
`    with open(line[:-4]+".json","w") as f:
`

it will save the json file in the same dir as your images.

Closing the issue. 
Thanks for your effort on this great repo!

**Comment by musdfakoc** [comment]
thanks that fixed the error for me too. great work
